##Workflow to validate packer..
name: Build Jenkins AMI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: "AKIA3FLD4S4RQROHAOFE"
          aws-secret-access-key: "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"
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3"

      - name: Initialize Packer
        run: packer init packer/jenkins-ami.pkr.hcl

      - name: Format Packer template
        run: packer fmt -check packer/jenkins-ami.pkr.hcl
 
      - name: Validate Packer template
        run: packer validate packer/jenkins-ami.pkr.hcl  

     

