name: Packer Build Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  ami_build:
    name: Building Image with Jenkins Configurations
    runs-on: ubuntu-latest
    outputs:
      AMI_ID: ${{ steps.GET_AMI.outputs.AMI_ID }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY_ID }}
          aws-region: us-east-1

      - name: Create & configure Packer variables
        run: |
          touch jenkinsami.pkrvars.hcl
          echo ami_prefix=\"Csye-7125-Packer-Image\" >> jenkinsami.pkrvars.hcl
          echo OS=\"Ubuntu\" >> jenkinsami.pkrvars.hcl
          echo ssh_username=\"ubuntu\" >> jenkinsami.pkrvars.hcl
          echo source_ami=\"ami-04b70fa74e45c3917\" >> jenkinsami.pkrvars.hcl
          echo subnet_id=\"subnet-0fed40e7e8324ea27\" >> jenkinsami.pkrvars.hcl
          echo aws_region=\"us-east-1\" >> jenkinsami.pkrvars.hcl
          echo instance_type=\"t2.micro\" >> jenkinsami.pkrvars.hcl
          echo device_name=\"/dev/sda1\" >> jenkinsami.pkrvars.hcl
          echo ami_users=\"[992382384015, 767398141113]\" >> jenkinsami.pkrvars.hcl
          echo ami_name=\"Jenkins-AMI\" >> jenkinsami.pkrvars.hcl

      - name: Packer Init
        run: packer init ./packer/jenkins-ami.pkr.hcl

      - name: Packer Build
        env:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY_ID }}
        run: packer build -var-file=jenkinsami.pkrvars.hcl ./packer/jenkins-ami.pkr.hcl

      - name: GET AMI ID
        id: GET_AMI
        run: |
          AMI_ID=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)
          echo $AMI_ID
          echo "AMI_ID=$AMI_ID" >> "$GITHUB_OUTPUT"
