name: Packer Build Workflo

on:
  push:
    branches:
      - main

jobs:
  ami_build:
    name: Building Image with Jenkins Configurations
    runs-on: ubuntu-latest
    outputs:
      AMI_ID: ${{ steps.GET_AMI.outputs.AMI_ID }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY_ID }}
          aws-region: us-east-1

      - name: Create & configure Packer variables
        run: |
          touch jenkinsami.pkrvars.hcl
          echo ami_prefix=\"${{ secrets.AMI_PREFIX }}\" >> jenkinsami.pkrvars.hcl
          echo OS=\"${{ secrets.OS }}\" >> jenkinsami.pkrvars.hcl
          echo ssh_username=\"${{ secrets.SSH_USERNAME }}\" >> jenkinsami.pkrvars.hcl
          echo source_ami=\"${{ secrets.SOURCE_AMI }}\" >> jenkinsami.pkrvars.hcl
          echo subnet_id=\"${{ secrets.SUBNET_ID }}\" >> jenkinsami.pkrvars.hcl
          echo aws_region=\"${{ secrets.AWS_REGION }}\" >> jenkinsami.pkrvars.hcl
          echo instance_type=\"${{ secrets.INSTANCE_TYPE }}\" >> jenkinsami.pkrvars.hcl
          echo device_name=\"${{ secrets.DEVICE_NAME }}\" >> jenkinsami.pkrvars.hcl
          echo ami_name=\"${{ secrets.AMI_NAME }}\" >> jenkinsami.pkrvars.hcl

      - name: Packer Init
        run: packer init ./packer/jenkins-ami.pkr.hcl

      - name: Packer Build
        env:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY_ID }}
        run: packer build -var-file=jenkinsami.pkrvars.hcl ./packer/jenkins-ami.pkr.hcl

      - name: GET AMI ID
        id: GET_AMI
        run: |
          AMI_ID=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)
          echo $AMI_ID
          echo "AMI_ID=$AMI_ID" >> "$GITHUB_OUTPUT"
